name: Daily Raindrop Roundup

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  roundup:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: curl, json
        
    - name: Run daily roundup
      env:
        RAINDROP_ACCESS_TOKEN: ${{ secrets.RAINDROP_ACCESS_TOKEN }}
      run: |
        php daily_roundup.php
        
    - name: Email HTML file
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Daily Roundup - $(date +'%B %d, %Y')"
        to: ${{ secrets.EMAIL_TO }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: "Your daily roundup for $(date +'%B %d, %Y') is attached."
        attachments: daily_roundup_*.html
        
    - name: Upload HTML file
      uses: actions/upload-artifact@v4
      with:
        name: daily-roundup-html
        path: daily_roundup_*.html
